//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concours2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccomdationType
    {
        public AccomdationType()
        {
            this.AccomdationDatas = new HashSet<AccomdationData>();
            this.AccomndationPictures = new HashSet<AccomndationPicture>();
        }
    
        public int AccomndationTypeID { get; set; }
        public string AccomndationType { get; set; }
        public Nullable<double> AccomndationPricePerNight { get; set; }
    
        public virtual ICollection<AccomdationData> AccomdationDatas { get; set; }
        public virtual ICollection<AccomndationPicture> AccomndationPictures { get; set; }
    }
}
