//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concours2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccomdationData
    {
        public int AccomdationID { get; set; }
        public string UserEmail { get; set; }
        public Nullable<System.DateTime> StarDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string AddedByEmail { get; set; }
        public Nullable<int> AccomdationTypeID { get; set; }
    
        public virtual AccomdationType AccomdationType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
