//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concours2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.AccomdationDatas = new HashSet<AccomdationData>();
            this.AccomdationDatas1 = new HashSet<AccomdationData>();
        }
    
        public string Email { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public string Gender { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string MobileNo { get; set; }
        public string Photo { get; set; }
        public string RoleID { get; set; }
    
        public virtual ICollection<AccomdationData> AccomdationDatas { get; set; }
        public virtual ICollection<AccomdationData> AccomdationDatas1 { get; set; }
        public virtual Role Role { get; set; }
    }
}
